name: Deploy Next.js to HostGator

on:
  push:
    branches:
      - main # O deploy acontecerá sempre que a branch main for atualizada

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Mesma versão do seu ambiente local ou superior

      - name: Install dependencies
        run: npm ci # Usa npm ci para instabilidades mais seguras usando package-lock.json

      - name: Build Next.js
        run: npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/ # Pasta onde o Next.js gera o site estático
          server-dir: ./italoferreiradoreaco1774445031000.1612207.meusitehostgator.com.br/ # Pasta correta do domínio 000
